### ISSUE TITLE
"Icon" setting default can be simplified to fa-circle-h

### ISSUE THREAD

**Issue by shemetz** [eryon/hero-shmero-points#1]
For the setting's default value, instead of `fa-hospital-symbol`, you can use `fa-circle-h`.  This is better because it helps users immediately see a way to use a different letter -- for example, `fa-circle-v` for Villain Points.

**Comment by eryon** [comment]
Fair point. I will look into expanding that hint text, but I want to leave the actual default the same as what the [system uses](https://github.com/foundryvtt/pf2e/blob/eac080ea16fe791d53ffef342629cead786ae88f/static/templates/actors/character/partials/header.hbs#L11).
