### ISSUE TITLE
No english support for "a/an" or for pluralization

### ISSUE THREAD

**Issue by shemetz** [eryon/hero-shmero-points#2]
Currently the code just works with replacement, so replacing Hero Point with e.g. Antihero Points will cause sentences like "Reroll using a Antihero Point", using 'a' rather than the more correct 'an'.  Similarly, pluralization could be wrong if a user uses e.g. 'Benny' which becomes 'Bennys' rather than 'Bennies'.

I think the solution for this needs to be three settings:  simple singular, singular with indefinite article, and plural.

default to

1. `Hero Point`
2. `a Hero Point
3. `Hero Points`

and then expect e.g.

1. `Antihero Point`
2. `an Antihero Point`
3. `Antihero Points`

Sure, it's triple the amount of effort for users, but it's quick and only has to be done once.

**Comment by eryon** [comment]
Thanks for the suggestion. I've redesigned the settings and replacement logic to support this 🎉
